name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # optional
          MODEL: gpt-3.5-turbo
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          LANGUAGE: Korean
          PROMPT: |
            이 PR의 코드를 검토하고 다음 측면에서 자세한 피드백을 제공해주세요:
            
            1. 코드 품질: 가독성, 일관성, 모범 사례 준수 여부
            2. 잠재적인 버그나 논리적 오류
            3. 성능 개선 가능성
            4. 보안 취약점
            5. 테스트 커버리지 및 예외 처리
            6. 코드 중복 및 리팩토링 기회
            
            코드의 좋은 점도 함께 언급하고, 개선이 필요한 부분에 대해서는 구체적인 수정 방법을 제안해주세요.
            비판적이기보다는 건설적인 피드백을 제공하고, 중요한 이슈부터 우선순위를 두어 설명해주세요.